import React from "react";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import Style from "../Components/test.module.scss";

const Test = () => {
  return (
    <>
      <Head>
        <title>Pass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main></main>
    </>
  );
};

export default Test;
