import Head from 'next/head'
import Image from 'next/image'
import { useRouter } from 'next/router'
import { useLayoutEffect } from 'react';
import isEmailConfirmed from '@/lib/axios/isEmailConfirmed';
import { useState } from 'react';


import axios, { AxiosError } from "axios";
import config from '@/config.json';
import EmailConfirmatioin from './[emailConfirmationToken]';

const API_ENDPOINT = config.apiEndpoint;

export default function EmailConfirmation() {
    const router = useRouter();
    const [msg, setMsg] = useState<string>('');
    console.log('router here', router);
    useLayoutEffect(
        () => {
            let token = router.query.emailConfirmationToken;
            console.log('token here', token);

            const isConfirmed = async() => {
                try {
                    const response = await axios.post(`${API_ENDPOINT}/users/email/confirmation/${token}`);
                    console.log(JSON.stringify(response?.data));

                    setMsg('Email is confirmed successfully')
                } catch(err) {
                    setMsg('something wrong happened')
                }
            }

            isConfirmed();
        }, [router.query.emailConfirmationToken])

    if (msg === '')
        return <div>Loading</div>;


    return (
        <>
            <Head>
                <title>Pass</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <div>{msg}</div>
            </main>
        </>
    )
}


