import Head from 'next/head'
import Image from 'next/image'
import { faInfoCircle, faCheck } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import axios, { AxiosError } from "axios";
import { API_URL } from "@/lib/utils/urls";
import { useState, useEffect } from 'react';
import styles from '@/styles/pages/forgotPassword.module.scss';
import { EMAIL_REGEX } from '@/lib/utils/regex';
import {fireSuccess,fireError} from '@/lib/utils/toasts'

export default function ForgotPassword() {
    // const [value, setValue] = useState('');
    // const [validEmail, setValidEmail] = useState(false);
    // const [loading,setLoading] = useState(false);

    // useEffect(() => {
    //     const validateEmail = EMAIL_REGEX.test(value);
    //     setValidEmail(validateEmail);
    //     if (!validateEmail)
    //         setErrMsg('Please enter a valid email');
    //     else
    //         setErrMsg('');
    // }, [value]);

    // const handleSubmit = async () => {
    //     const validateEmail = EMAIL_REGEX.test(value);
    //     if (!validateEmail) {
    //         fireError('Please enter a valid email');
    //         return;
    //     }

    //     try {
    //         setLoading(true);
    //         const response = await axios.post(`${API_URL}/users/forgot-password/`, {
    //             "email": value
    //         }
    //         );
    //         console.log(JSON.stringify(response?.data));
            
    //         setLoading(false);
    //     } catch (err) {
    //         setLoading(false);
    //         const error = err as AxiosError;
    //         console.log(error)
    //         if (error?.response) {
    //             //@ts-ignore
    //             fireError(error.response?.data?.message);
    //         }
    //         else {
    //             fireError('Something went wrong');
    //         }
    //     }
    // };

  

    // return (
    //     <>
    //         <Head>
    //             <title>forgot password</title>
    //             <meta name="description" content="Generated by create next app" />
    //             <meta name="viewport" content="width=device-width, initial-scale=1" />
    //             <link rel="icon" href="/favicon.ico" />
    //         </Head>
    //         <main >
    //             <div className={styles.container}>
    //                 <div className={styles.card}>
    //                     <h1 className={styles.title}>Forgot Password</h1>
    //                     <form onSubmit={handleSubmit} className={styles.content}>
    //                         <div className={styles.in}>
    //                             <label className={styles.label}>Email:</label>
    //                             <input
    //                                 type="email"
    //                                 value={value}
    //                                 onChange={(e) => setValue(e.target.value)}
    //                                 placeholder="Enter your email"
    //                                 className={styles.input}
    //                             />
    //                         </div>

    //                         <button type="submit" className={styles.button}>Submit</button>
    //                     </form>
    //                 </div>
    //             </div>
    //         </main>
    //     </>
    // )

    return <div>under development</div>
}

