import Navbar from "@/components/Navbar";
import Head from "next/head";
import Image from "next/image";
// import { Inter } from '@next/font/google'
import Hero from "./../components/Hero";

import GlassBox from "@/components/landing/GlassBox";
import BlueCards from "@/components/landing/BlueCards";
import HowItWorks from "@/components/landing/HowItWorks";
import JoinPassToday from "@/components/landing/JoinPassToday";
import HowToStart from "@/components/landing/HowToStart";
import BlueFilledCards from "@/components/landing/BlueFilledCards";
import Footer from "@/components/landing/Footer";
import { useEffect } from "react";

import useTrackStore from "@/lib/zustand/stores/useTrackStore";

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [visitedHomeAfterLogin, setVisitedHomeAfterLogin] = useTrackStore(
    (state) => [state.visitedHomeAfterLogin, state.setVisitedHomeAfterLogin]
  );

  useEffect(() => {
    if (visitedHomeAfterLogin) {
      window.location.reload();
      setVisitedHomeAfterLogin(false);
    }
  }, []);

  if (visitedHomeAfterLogin) {
    return null;
  }

  return (
    <>
      <Head>
        <title>Pass</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />

        <GlassBox />
        <HowItWorks />
        <JoinPassToday />
        <BlueCards />
        <HowToStart />
        <BlueFilledCards />
        <Footer />
      </main>
    </>
  );
}
